### ISSUE TITLE
Website does not handle multi-tiered markdown lists

### ISSUE THREAD

**Issue by rcorre** [D-Programming-Language/dub-registry#105]
A nested markdown list
- Like
  - this
  - one

Is rendered

- Like
- this
- one

Compare the rendering of the 'overview' section of my README.md on [github](https://github.com/rcorre/jsonizer) vs on [code.dlang.org](http://code.dlang.org/packages/jsonizer).

**Comment by s-ludwig** [comment]
This appears to be a bug in vibe.d's Markdown parser. It expects at least four spaces in front of the nested list items instead of just two.

**Comment by s-ludwig** [comment]
Moving to vibe.d: https://github.com/rejectedsoftware/vibe.d/issues/1046
