### ISSUE TITLE
travis-ci repeatedly failing to request http://code.dlang.org/download/LATEST

### ISSUE THREAD

**Issue by Extrawurst** [D-Programming-Language/dub-registry#109]
since today some builds randomly fail with this line:

> The command "LATEST_DUB=$(curl http://code.dlang.org/download/LATEST)" failed and exited with 22 during .

hope this is the right place for this ticket. maybe unrelated but also http://forum.rejectedsoftware.com/ is randomly down today and back after one or two reloads... (is the dub-repo still hosted there too?)

**Comment by s-ludwig** [comment]
The server for some reason constantly ran out of memory today and in turn randomly killed processes. I think it was because multiple instances of a watchdog script was running. Everything seems to be running normal now (with only one instance of the script running).
