### ISSUE TITLE
Strange JSON parsing error

### ISSUE THREAD

**Issue by buggins** [D-Programming-Language/dub-registry#110]
My package dlangui is not being updated by DUB registry anymore
Last updated version is 0.6.11 while latest release on GitHub is 0.6.20

Package errors:
Branch ~gh-pages: Got JSON of type undefined, expected object.
Branch ~master: (67): Error: Expected '}' or ',' - got '"'.
Version 0.5.34: (40): Error: Expected '}' or ',' - got '"'.

But I'm able to build package using DUB, and Travis CI build is passed.

Cannot force update manually.
I've updated dub.json to change line numbering, but still see error in the same line.
Probably, package is just stopped being updated by registry.

**Comment by s-ludwig** [comment]
It turned out that the cause is a failure storing the updated version list in MongoDB. Incidentially, this also turned out to be the reason why updating the package list periodically got stalled. I'm not yet sure if this is a size issue or something else.

**Comment by s-ludwig** [comment]
Still need to investigate why there is a difference between the original BSON and the re-serialized version. Both versions are equal when comparing the JSON stringify output.
