### ISSUE TITLE
A way to "trigger update" for packages you don't own

### ISSUE THREAD

**Issue by p0nce** [D-Programming-Language/dub-registry#116]
I'm currently waiting for a release tag to be registered on the DUB registry.
If the maintainer doesn't click the button it can delay a fix by some time (hours maybe? I don't know). 
So I thought registered users [with at least one package] could be given the chance to update the registry for other's packages.

**Comment by s-ludwig** [comment]
The update interval is currently 30 minutes, so not *that* bad. But the long-term plan is to support push notifications for immediate updates, but that requires an OAuth connection to GitHub for each repository.

**Comment by p0nce** [comment]
OK. It was just a tag name `v2.066` hence not recognized. Already happened to me with tags without a v- prefix like `1.0.0` instead of `v1.0.0`.
