### ISSUE TITLE
Package list (front page) loads extremely slow

### ISSUE THREAD

**Issue by MartinNowak** [D-Programming-Language/dub-registry#128]
Takes consistently more than 2 seconds. Could it be that you're performing some expensive db queries (e.g. w/o index)?

**Comment by s-ludwig** [comment]
The problem is that currently the information for each package is queried individually. I'll change that to a fused query.

**Comment by s-ludwig** [comment]
Must be more. I've added some more packages to my local DB and it still gets slower. I'll profile this tomorrow.

**Comment by s-ludwig** [comment]
Turns out dub-registry was actually fine. The problem was that vibe.d was buffering up the whole response in memory instead of sending on the fly. I still need to see why this buffering process was so inefficient - maybe an issue with the `realloc()` implementation of one of the allocators.

**Comment by MartinNowak** [comment]
Thanks, ultimately the approach to show all packages on the front page is flawed though, maybe time to think of paginating the list. But then again this might wait for a frontend makeover.

**Comment by s-ludwig** [comment]
Sure, there will be no way around that. Eventually quite some things will also need to be moved to the database (filtering, sorting), or completely removed (package information cache).
