### ISSUE TITLE
no icon for the packages that are registered in the category "Development library"

### ISSUE THREAD

**Issue by BBasile** [D-Programming-Language/dub-registry#132]
~~If the DUB json (maybe sdl too) of a package specify~~

~~`"targetType" : "staticLibrary",`~~

~~then in the online list it's displayed with a white icon and with the hint "Unknown".~~

**Comment by MartinNowak** [comment]
Why do you explicitly use `staticLibrary`? It's more preferable to just use `library` and leave any static vs. dynamic library decision to dub.
Your iz library has an unknow icon b/c it's missing details categories.
http://code.dlang.org/packages/iz.json

**Comment by BBasile** [comment]
Right, the bug is actually that if we set a package category to _Developmenet Library_ , a white icon is displayed. Since this choice was stored I couldn't imagine it was invalid.

**Comment by BBasile** [comment]
To be clear, this choice seems valid:

![invalid_cat_dub](https://cloud.githubusercontent.com/assets/16154339/12541830/0170e820-c31c-11e5-8851-2c90b9dce8b0.png)

because the first time one registers a package the choice is stored. But actually it's not valid and a white icon is displayed.
