### ISSUE TITLE
JSON parsing error

### ISSUE THREAD

**Issue by MartinNowak** [D-Programming-Language/dub-registry#83]
Got that for my package, looks like an unexpected github response.
http://code.dlang.org/my_packages/bloom

Package errors:
Branch ~gh-pages: Got JSON of type undefined, expected object.

Not sure yet, what triggered the request.

**Comment by buggins** [comment]
I would suggest to disable checking of gh-pages branches on GitHub, because it's intended for web sites, not dub projects.

**Comment by buggins** [comment]
I have dub.json parsing error on DlangUI library reported by dub registry, although dub builds my project correctly.

Branch ~gh-pages: Got JSON of type undefined, expected object.
Branch ~master: (67): Error: Expected '}' or ',' - got '"'.
Version 0.5.34: (40): Error: Expected '}' or ',' - got '"'.

gh-pages branch error is ok, but I don't understand what is a problem with ~master
