### ISSUE TITLE
Would be nice to have a "search" feature

### ISSUE THREAD

**Issue by grogancolin** [D-Programming-Language/dub-registry#86]
It would be good to have a REST api for searching for packages on the registry.

Something like
/search?id-like="searchString"

And the service would return JSON with all packages in the registry that are close to "searchString".

This could be done with MongoConnector and ElasticSearch 
(Info here -> http://blog.mongodb.org/post/95839709598/how-to-perform-fuzzy-matching-with-mongo-connector).

**Comment by grogancolin** [comment]
So, currently I have the search interface in
/api/search?q=space%20seperated%20search%20terms

The search function then returns a json string like:
{
    "space" : [ <close matches> ],
    "seperated" : [etc etc]
}

On the dub end it will then be trivial to parse this into a nice help text.

This an ok direction?

````D
	void querySearch(HTTPServerRequest req, HTTPServerResponse res){
		auto q = "q" in req.query;
		if(q == null) {
			res.statusCode = 400;
			res.writeJsonBody("Error: Must pass query parameter");
			return;
		}
		string[] queryStrings = (*q).split();

		// do the search, putting the results into a json object
		Json json = Json.emptyObject;
		foreach(str; queryStrings){
			json[str] = m_registry.searchPackages([str]).array;
		}
		res.statusCode = 200;
		res.writeJsonBody(json);
	}
```

I'll create a pull request tomorrow...

**Comment by s-ludwig** [comment]
Sounds good. Except that I think it would be better to change `DubRegistryAPI` from a web interface to a REST interface. I didn't notice when it was added, but before we let this grow larger and larger, I we should better fix this first.

BTW, regarding the query string handling. Considering that we might implement a more clever way to score multiple search words and that multiple queries could be used to achieve the proposed behavior, I'd tend to send all query words to the search function at once and return only a single list. Do you have a certain use case for this?

**Comment by grogancolin** [comment]
I think a REST interface would be more suited to this also. 

The use case for this was more on the dub end to print to the end user something like:
```
you entered  :  Close matches
dubb             :   [ dub, dub-registry ]
vibed             :  [ vibe-d ]
```
(Apologies for poor formatting)

To do that I need to keep track of what query string is close to what packages. That's what the json[str] is for. Passing all query strings at once into searchPackages() wont let me keep track of this..

Maybe re-doing (or making an overload) of searchPackages that takes in a Json and returns a Json object constructed like the above?

Obviously, this will all need to be re-worked when elastic search is used, maybe it'd be better to go and implement that now rather than later?

**Comment by s-ludwig** [comment]
I see. You could of course just query each library with a separate request. But if we need this for efficiency reasons (I think a keep-alive connection should be enough, though), we could for example also change the signature to accept a parameter `(string[] q)`. This would allow calling it like this: `GET /api/search?q=first+query&q=second+query`. The response would then contain an array of result sets. I'd probably use a different URL, though, something like `GET /api/multi_search`, so that the usual case only contains a simple single result set.

**Comment by MartinNowak** [comment]
I change the api to use a REST interface.
https://github.com/D-Programming-Language/dub-registry/pull/103
Should be fairly simple to go on from here.

**Comment by MartinNowak** [comment]
See #121.
