### ISSUE TITLE
provide a copy+paste link to add a dub shield to a project

### ISSUE THREAD

**Issue by MartinNowak** [D-Programming-Language/dub-registry#96]
A few projects start to add backlink shields to code.dlang.org.
We should provide a common method to create such shields, that shows the latest version.

https://github.com/kiith-sa/dmarkdown
https://github.com/MartinNowak/qcheck

A nice extra feature would be to copy the `"qcheck": "~>0.1.0"` dependency line into the clipboard when clicking the link.

**Comment by MartinNowak** [comment]
Shields now available on http://shields.io/.

**Comment by greenify** [comment]
> Shields now available on http://shields.io/.

this should now be as easy as adding 

```
https://img.shields.io/dub/v/<package-name>.svg (latest version)
https://img.shields.io/dub/dm/<package-name>.svg (monthly downloads)
```

**Comment by s-ludwig** [comment]
I have a local branch where I started to add this. The main issue is just creating a nice UI for the many different possible variants (daily/weekly/monthly/all x total/latest/specific) instead of just listing them side by side.

**Comment by MartinNowak** [comment]
I think we should make a good selection, e.g. total downloads and version, and can link to shields.io for more options.

**Comment by MartinNowak** [comment]
Adding a select box for versions (including all and latest) and changing total downloads accordingly could be done as well.
