### ISSUE TITLE
Enable Travis-CI

### ISSUE THREAD

**Issue by s-ludwig** [D-Programming-Language/dub-registry#99]
I've added a .travis.yml to the repository, but lack the admin access rights required to enable Travis-CI for the repository. Can someone with the required authorization do that? (@WalterBright?)

**Comment by MartinNowak** [comment]
We might also ask @andralex or maybe @braddr to toggle the switch.

**Comment by MartinNowak** [comment]
Thanks to Andrei, this is our first dub-registry test.
https://travis-ci.org/D-Programming-Language/dub-registry/builds/56667946
